version: '3'

services:
  # ===========================
  #        REVERSE PROXY
  # ===========================
  proxy:
    build: .
    container_name: "nginx-proxy"
    ports:
      - "80:80"
      - "443:443"

